apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod
namePrefix: prod-asia-

resources:
- ../../base

components:
  - ../../variants/development

patchesStrategicMerge:
- replicas.yml
- resources.yml
- settings.yml