---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  template:
    spec:
      containers:
      - name: nginx
        resources:
          requests:
            memory: "28Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"